# Generated by Django 3.2.4 on 2026-05-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20250712_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('usia', models.CharField(choices=[('< 20', '< 20 tahun'), ('20-30', '20–30 tahun'), ('31-40', '31–40 tahun'), ('41-50', '41–50 tahun'), ('> 50', '> 50 tahun')], max_length=10)),
                ('pendidikan_terakhir', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA/SMK'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=5)),
                ('umkm', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Responden',
                'db_table': 'responden',
            },
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variabel', models.CharField(choices=[('PEOU', 'Perceived Easy of Use'), ('PU', 'Perceived Usefulness'), ('CONF', 'Confirmation'), ('ATT', 'Attitude'), ('TRST', 'Trust'), ('SAT', 'Satisfaction'), ('CI', 'Continuance Intention')], max_length=5)),
                ('kode_item', models.CharField(max_length=10)),
                ('skor', models.PositiveSmallIntegerField(choices=[(1, 'STS – Sangat Tidak Setuju'), (2, 'TS – Tidak Setuju'), (3, 'S – Setuju'), (4, 'SS – Sangat Setuju')])),
                ('responden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='inventory.responden')),
            ],
            options={
                'db_table': 'jawaban',
                'unique_together': {('responden', 'kode_item')},
            },
        ),
    ]
